### ISSUE TITLE
Proposal to contribute

### ISSUE THREAD

**Issue by Vimal-Mudalagi** [kishan0921/hacktoberfest2024#32]
Hi Kishan,

I saw your project with "Hello World" programs in different languages. I'd like to help by adding more languages or improving the current code. Is that okay? Let me know if there are any rules I should follow.

Thanks!

**Comment by kishan0921** [comment]
Hii Vimal,

I’d like to clarify the guidelines for contributions. There are no strict rules! If you’d like to contribute, feel free to add a "Hello World" program in any programming language. I’ll be more than happy to accept your contribution.

**Comment by Vimal-Mudalagi** [comment]
I have sent a PR. I added Hello World in rust and added Majority Element- a Leetcode Solution using Moore's algo.
Let me know if you need anything from my side.
